### ISSUE TITLE
FirebaseInstanceIdService is deprecated

### ISSUE THREAD

**Issue by burekas7** [DimitarStoyanoff/Notifications#4]
Hi,

First thanks for the guide here:
https://www.pluralsight.com/guides/push-notifications-with-firebase-cloud-messaging

Second, can you update it? because "FirebaseInstanceIdService is deprecated"
According to this:
https://medium.com/android-school/firebaseinstanceidservice-is-deprecated-50651f17a148

Thanks.

**Comment by DimitarStoyanoff** [comment]
@burekas7  updated it, sorry for the delay. Thanks for the reminder.
