### ISSUE TITLE
Migrate to AndroidX, add API 26 support

### ISSUE THREAD

**Issue by CoolMind** [DimitarStoyanoff/Notifications#5]
Thank you for the tutorial! Please, remove C2DM, because it has not been used since 2015 (I think).
As many Google libraries have moved to AndroidX, could you also migrate the project?
Also add API 26 support (Android channels).

**Comment by DimitarStoyanoff** [comment]
@CoolMind  Sorry for taking so long. Updated dependencies, and the codebase is now in Kotlin. As for the notification channels, they were already implemented. Thanks for the support.
